DROP TABLE IF EXISTS raw_payment_actions;

CREATE TABLE raw_payment_actions (
  ts timestamp without time zone,
  b2_until_ts timestamp without time zone,
  period_end_ts timestamp without time zone,
  next_billilng_ts timestamp without time zone,
  user_id varchar(64),
  base_subscription_id varchar(64),
  base_plan_id int,
  gateway_provided_subscription_id varchar(64),
  gateway_provided_plan_id varchar(256),
  gateway_provided_customer_id varchar(64),
  action varchar(256),
  is_recurring_subscription boolean,
  subscription_interval varchar(256),
  client varchar(256),
  gateway varchar(256),
  country_code char(2),
  currency_code char(3),
  amount_paid decimal,
  estimated_amount_paid_usd decimal,
  estimated_listing_price_usd decimal,
  list_price decimal,
  discounted_amount decimal,
  used_coupon boolean,
  percent_off smallint,
  counpon_id int,
  cancellation_reason varchar(256),
  client_install_identity varchar(64),
  account_type varchar(256),
  dispute_status varchar(256),
  dispute_reason varchar(256),
  dispute_filed_ts timestamp without time zone,
  dispute_gateway_provided_dispute_id varchar(256),
  dispute_resolved_ts timestamp without time zone,
  dispute_in_favor_of varchar(256),
  paypal_suspended_remotely boolean,
  apple_product_id varchar(256),
  apple_original_transaction_id varchar(64),
  gift_purchase_id varchar(64),
  gwallet_order_id varchar(64),
  payment_request_method varchar(32),
  tax_price decimal,
  tax_style char(9),
  refund_or_revoke_reason varchar(255),
  chargebee_upstream_gateway varchar(6),
  chargebee_upstream_gateway_provided_customer_id varchar(64),
  chargebee_upstream_gateway_porivded_subscription_id varchar(64),
  chargebee_upstream_gateway_provided_plan_id varchar(256),
  chargebee_transaction_id varchar(64)
);

-- NOTE: the path here is relative to the "db" directory
COPY raw_payment_actions FROM '../dataset_2021-11-16.csv' CSV HEADER;
