default:
  outputs:

    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '55432'
      port: 55432
      dbname: warehouse
      schema: dbt
      threads: 4

  target: dev
